spring:
  application:
    name: FeignServer
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/devicedb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: classpath*:mapper/*.xml

server:
  port: 7111

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      leaseRenewalIntervalInSeconds: 10
      metadataMap:
        instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}
