package com.hzyw.iot.util;

/**
 * @author Administrator
 *
 */
public class IotInfoMethod {
 
    public static final String[] tomda_charger_signls = {
    		"109050:TOMDA_EBIKE_FAULT_ES",
    		"109051:TOMDA_EBIKE_FAULT_VOLTAGE_UPLIMIT",
    		"109052:TOMDA_EBIKE_FAULT_VOLTAGE_DOWNLIMIT",
    		"109053:TOMDA_EBIKE_FAULT_CURRENT_UPLIMIT",
    		"109054:TOMDA_EBIKE_FAULT_CURRENT_DOWNLIMIT",
    		"109055:TOMDA_EBIKE_FAULT_TEMPERATURE_UPLIMIT",
    		"109056:TOMDA_EBIKE_FAULT_TEMPERATURE_DOWNLIMIT",
    		"109057:TOMDA_EBIKE_FAULT_LEAK_CURRENT",
    		"109058:TOMDA_EBIKE_FAULT_GND",
    		"109059:TOMDA_EBIKE_FAULT_TILT",
    		"109060:TOMDA_EBIKE_FAULT_EM_ERROR",
    		"109061:TOMDA_EBIKE_FAULT_GUN_TEMPERATURE_UPLIMIT",
    		"109062:TOMDA_EBIKE_FAULT_GUN_TEMPERATURE_DOWNLIMIT",   
    };
    
}
