spring:
  application:
    name: FeignClient

server:
  port: 7211


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
  server:
    enable-self-preservation: false # only develop

#eureka:
#  password: password
#  client:
#    serviceUrl:
#      defaultZone: https://user:${eureka.password}@localhost:8761/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000


#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false